### DISCUSSION TITLE
git action을 이용한 서버 연결과 자동으로 git pull하기

### DISCUSSION THREAD

**Discussion by HYU-kbs** [boostcampaitech2/final-project-level3-cv-14#23] [Show and tell]
제 public git repository에서 실험한 결과를 공유드립니다.

## git 아이디와 비밀번호 설정하기

먼저 aistage서버에서 git repo를 pull합니다.

git repo를 pull할 때마다 아이디와 비밀번호를 묻게되는데, 이를 파일로 저장해 더 이상 묻지 않도록 했습니다.

이 방법은 파일에 내 아이디와 개인 토큰 값이 그대로 저장되어 보안에 취약하다고 합니다.
https://stackoverflow.com/questions/11403407/git-asks-for-username-every-time-i-push

```shell
git config credential.helper store
git pull origin Integrated
Username: HYU-kbs
Password: <개인 토큰 값>

```

## nohup을 이용한 백그라운드에서 서버 실행

다음 방법으로 streamlit 서버와 task를 담당할 서버를 실행합니다.

```shell
# 파일이 변경될 때 서버를 항상 자동으로 실행하며 logging파일 nohup.out이 생기지 않는다.
nohup streamlit run WebServer/Server_SRD.py --server.runOnSave true --server.port 6006 > /dev/null 2>&1 &
cd SuperResolution
nohup python Server.py >/dev/null 2>&1 &
```
## git action 만들기

이후 git action을 생성합니다. 

제 public repo에서 실험할 때 secrets.HOST, secrets.USERNAME, secrets.SSH_KEY를 설정했습니다.

```yaml
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: stop, pull and rerun

on:
  push:
    # master branch에 push가 일어날 때
    branches: [ master ]

jobs:
  stop, pull and rerun:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 2228
        script: |
            kill -9 $(ps -A | grep python | awk '{print $1}')
            cd /opt/ml/final-project/
            git pull origin Integrated
            cd SuperResolution
            nohup python Server.py >/dev/null 2>&1 &
```
